#include "constants/songs.h"	
	
	.align 2

gSongTable::
	song mus_dummy, 0, 0
	song se_use_item, 1, 1
	song se_pc_login, 1, 1
	song se_pc_off, 1, 1
	song se_pc_on, 1, 1
	song se_select, 2, 2
	song se_win_open, 1, 1
	song se_wall_hit, 2, 2
	song se_door, 1, 1
	song se_exit, 1, 1
	song se_ledge, 1, 1
	song se_bike_bell, 1, 1
	song se_not_effective, 1, 1
	song se_effective, 1, 1
	song se_super_effective, 1, 1
	song se_ball_open, 1, 1
	song se_faint, 1, 1
	song se_flee, 1, 1
	song se_sliding_door, 1, 1
	song se_ship, 1, 1
	song se_bang, 1, 1
	song se_pin, 1, 1
	song se_boo, 1, 1
	song se_ball, 1, 1
	song se_contest_place, 2, 2
	song se_a, 1, 1
	song se_i, 1, 1
	song se_u, 1, 1
	song se_e, 1, 1
	song se_o, 1, 1
	song se_n, 1, 1
	song se_success, 1, 1
	song se_failure, 1, 1
	song se_exp, 1, 1
	song se_bike_hop, 1, 1
	song se_switch, 1, 1
	song se_click, 1, 1
	song se_fu_zaku, 1, 1
	song se_contest_condition_lose, 1, 1
	song se_lavaridge_fall_warp, 1, 1
	song se_ice_stairs, 1, 1
	song se_ice_break, 1, 1
	song se_ice_crack, 1, 1
	song se_fall, 1, 1
	song se_unlock, 2, 2
	song se_warp_in, 1, 1
	song se_warp_out, 1, 1
	song se_repel, 1, 1
	song se_rotating_gate, 1, 1
	song se_truck_move, 1, 1
	song se_truck_stop, 1, 1
	song se_truck_unload, 2, 2
	song se_truck_door, 1, 1
	song se_berry_blender, 2, 2
	song se_card, 1, 1
	song se_save, 1, 1
	song se_ball_bounce_1, 1, 1
	song se_ball_bounce_2, 1, 1
	song se_ball_bounce_3, 1, 1
	song se_ball_bounce_4, 1, 1
	song se_ball_trade, 2, 2
	song se_ball_throw, 1, 1
	song se_note_c, 2, 2
	song se_note_d, 2, 2
	song se_note_e, 2, 2
	song se_note_f, 2, 2
	song se_note_g, 2, 2
	song se_note_a, 2, 2
	song se_note_b, 2, 2
	song se_note_c_high, 2, 2
	song se_puddle, 2, 2
	song se_bridge_walk, 2, 2
	song se_itemfinder, 1, 1
	song se_ding_dong, 1, 1
	song se_balloon_red, 2, 2
	song se_balloon_blue, 2, 2
	song se_balloon_yellow, 2, 2
	song se_breakable_door, 2, 2
	song se_mud_ball, 2, 2
	song se_field_poison, 1, 1
	song se_escalator, 1, 1
	song se_thunderstorm, 3, 3
	song se_thunderstorm_stop, 3, 3
	song se_downpour, 3, 3
	song se_downpour_stop, 3, 3
	song se_rain, 3, 3
	song se_rain_stop, 3, 3
	song se_thunder, 1, 1
	song se_thunder2, 1, 1
	song se_elevator, 1, 1
	song se_low_health, 3, 3
	song se_exp_max, 1, 1
	song se_roulette_ball, 2, 2
	song se_roulette_ball2, 2, 2
	song se_taillow_wing_flap, 1, 1
	song se_shop, 1, 1
	song se_contest_heart, 1, 1
	song se_contest_curtain_rise, 1, 1
	song se_contest_curtain_fall, 1, 1
	song se_contest_icon_change, 1, 1
	song se_contest_icon_clear, 1, 1
	song se_contest_mons_turn, 1, 1
	song se_shiny, 1, 1
	song se_intro_blast, 1, 1
	song se_mugshot, 1, 1
	song se_applause, 1, 1
	song se_vend, 1, 1
	song se_orb, 1, 1
	song se_dex_scroll, 1, 1
	song se_dex_page, 1, 1
	song se_pokenav_on, 1, 1
	song se_pokenav_off, 1, 1
	song se_dex_search, 1, 1
	song se_egg_hatch, 1, 1
	song se_ball_tray_enter, 1, 1
	song se_ball_tray_ball, 1, 1
	song se_ball_tray_exit, 2, 2
	song se_glass_flute, 1, 1
	song se_m_thunderbolt, 2, 2
	song se_m_thunderbolt2, 1, 1
	song se_m_harden, 1, 1
	song se_m_nightmare, 1, 1
	song se_m_vital_throw, 1, 1
	song se_m_vital_throw2, 1, 1
	song se_m_bubble, 1, 1
	song se_m_bubble2, 1, 1
	song se_m_bubble3, 1, 1
	song se_m_rain_dance, 1, 1
	song se_m_cut, 1, 1
	song se_m_string_shot, 1, 1
	song se_m_string_shot2, 1, 1
	song se_m_rock_throw, 1, 1
	song se_m_gust, 2, 2
	song se_m_gust2, 2, 2
	song se_m_double_slap, 1, 1
	song se_m_double_team, 1, 1
	song se_m_razor_wind, 1, 1
	song se_m_icy_wind, 1, 1
	song se_m_thunder_wave, 1, 1
	song se_m_comet_punch, 1, 1
	song se_m_mega_kick, 1, 1
	song se_m_mega_kick2, 1, 1
	song se_m_crabhammer, 1, 1
	song se_m_jump_kick, 1, 1
	song se_m_flame_wheel, 1, 1
	song se_m_flame_wheel2, 1, 1
	song se_m_flamethrower, 1, 1
	song se_m_fire_punch, 1, 1
	song se_m_toxic, 1, 1
	song se_m_sacred_fire, 1, 1
	song se_m_sacred_fire2, 2, 2
	song se_m_ember, 1, 1
	song se_m_take_down, 2, 2
	song se_m_blizzard, 1, 1
	song se_m_blizzard2, 1, 1
	song se_m_scratch, 1, 1
	song se_m_vicegrip, 1, 1
	song se_m_wing_attack, 1, 1
	song se_m_fly, 1, 1
	song se_m_sand_attack, 1, 1
	song se_m_razor_wind2, 1, 1
	song se_m_bite, 1, 1
	song se_m_headbutt, 1, 1
	song se_m_surf, 1, 1
	song se_m_hydro_pump, 1, 1
	song se_m_whirlpool, 1, 1
	song se_m_horn_attack, 1, 1
	song se_m_tail_whip, 2, 2
	song se_m_mist, 1, 1
	song se_m_poison_powder, 1, 1
	song se_m_bind, 2, 2
	song se_m_dragon_rage, 1, 1
	song se_m_sing, 1, 1
	song se_m_perish_song, 1, 1
	song se_m_pay_day, 1, 1
	song se_m_dig, 1, 1
	song se_m_dizzy_punch, 1, 1
	song se_m_self_destruct, 1, 1
	song se_m_explosion, 1, 1
	song se_m_absorb_2, 1, 1
	song se_m_absorb, 1, 1
	song se_m_screech, 1, 1
	song se_m_bubble_beam, 1, 1
	song se_m_bubble_beam2, 1, 1
	song se_m_supersonic, 1, 1
	song se_m_belly_drum, 1, 1
	song se_m_metronome, 1, 1
	song se_m_bonemerang, 1, 1
	song se_m_lick, 1, 1
	song se_m_psybeam, 1, 1
	song se_m_faint_attack, 1, 1
	song se_m_swords_dance, 1, 1
	song se_m_leer, 1, 1
	song se_m_swagger, 1, 1
	song se_m_swagger2, 1, 1
	song se_m_heal_bell, 1, 1
	song se_m_confuse_ray, 1, 1
	song se_m_snore, 1, 1
	song se_m_brick_break, 1, 1
	song se_m_giga_drain, 1, 1
	song se_m_psybeam2, 1, 1
	song se_m_solar_beam, 2, 2
	song se_m_petal_dance, 1, 1
	song se_m_teleport, 1, 1
	song se_m_minimize, 1, 1
	song se_m_sketch, 1, 1
	song se_m_swift, 1, 1
	song se_m_reflect, 1, 1
	song se_m_barrier, 1, 1
	song se_m_detect, 2, 2
	song se_m_lock_on, 1, 1
	song se_m_moonlight, 1, 1
	song se_m_charm, 1, 1
	song se_m_charge, 1, 1
	song se_m_strength, 1, 1
	song se_m_hyper_beam, 1, 1
	song se_m_waterfall, 1, 1
	song se_m_reversal, 1, 1
	song se_m_acid_armor, 1, 1
	song se_m_sandstorm, 1, 1
	song se_m_tri_attack, 1, 1
	song se_m_tri_attack2, 1, 1
	song se_m_encore, 1, 1
	song se_m_encore2, 2, 2
	song se_m_baton_pass, 1, 1
	song se_m_milk_drink, 1, 1
	song se_m_attract, 1, 1
	song se_m_attract2, 1, 1
	song se_m_morning_sun, 1, 1
	song se_m_flatter, 1, 1
	song se_m_sand_tomb, 1, 1
	song se_m_grasswhistle, 1, 1
	song se_m_spit_up, 1, 1
	song se_m_dive, 1, 1
	song se_m_earthquake, 2, 2
	song se_m_twister, 2, 2
	song se_m_sweet_scent, 1, 1
	song se_m_yawn, 1, 1
	song se_m_sky_uppercut, 2, 2
	song se_m_stat_increase, 1, 1
	song se_m_heat_wave, 1, 1
	song se_m_uproar, 1, 1
	song se_m_hail, 1, 1
	song se_m_cosmic_power, 2, 2
	song se_m_teeter_dance, 1, 1
	song se_m_stat_decrease, 1, 1
	song se_m_haze, 1, 1
	song se_m_hyper_beam2, 1, 1
	song se_rg_door, 1, 1
	song se_rg_card_flip, 1, 1
	song se_rg_card_flipping, 1, 1
	song se_rg_card_open, 1, 1
	song se_rg_bag_cursor, 1, 1
	song se_rg_bag_pocket, 1, 1
	song se_rg_ball_click, 1, 1
	song se_rg_shop, 1, 1
	song se_rg_ss_anne_horn, 1, 1
	song se_rg_help_open, 1, 1
	song se_rg_help_close, 1, 1
	song se_rg_help_error, 1, 1
	song se_rg_deoxys_move, 1, 1
	song se_rg_poke_jump_success, 1, 1
	song se_rg_poke_jump_failure, 1, 1
	song se_pokenav_call, 1, 1
	song se_pokenav_hang_up, 1, 1
	song se_arena_timeup1, 1, 1
	song se_arena_timeup2, 1, 1
	song se_pike_curtain_close, 1, 1
	song se_pike_curtain_open, 1, 1
	song se_sudowoodo_shake, 1, 1
	song mus_dummy, 0, 0
	song ph_trap_blend, 2, 2
	song ph_trap_held, 2, 2
	song ph_trap_solo, 2, 2
	song ph_face_blend, 2, 2
	song ph_face_held, 2, 2
	song ph_face_solo, 2, 2
	song ph_cloth_blend, 2, 2
	song ph_cloth_held, 2, 2
	song ph_cloth_solo, 2, 2
	song ph_dress_blend, 2, 2
	song ph_dress_held, 2, 2
	song ph_dress_solo, 2, 2
	song ph_fleece_blend, 2, 2
	song ph_fleece_held, 2, 2
	song ph_fleece_solo, 2, 2
	song ph_kit_blend, 2, 2
	song ph_kit_held, 2, 2
	song ph_kit_solo, 2, 2
	song ph_price_blend, 2, 2
	song ph_price_held, 2, 2
	song ph_price_solo, 2, 2
	song ph_lot_blend, 2, 2
	song ph_lot_held, 2, 2
	song ph_lot_solo, 2, 2
	song ph_goat_blend, 2, 2
	song ph_goat_held, 2, 2
	song ph_goat_solo, 2, 2
	song ph_thought_blend, 2, 2
	song ph_thought_held, 2, 2
	song ph_thought_solo, 2, 2
	song ph_choice_blend, 2, 2
	song ph_choice_held, 2, 2
	song ph_choice_solo, 2, 2
	song ph_mouth_blend, 2, 2
	song ph_mouth_held, 2, 2
	song ph_mouth_solo, 2, 2
	song ph_foot_blend, 2, 2
	song ph_foot_held, 2, 2
	song ph_foot_solo, 2, 2
	song ph_goose_blend, 2, 2
	song ph_goose_held, 2, 2
	song ph_goose_solo, 2, 2
	song ph_strut_blend, 2, 2
	song ph_strut_held, 2, 2
	song ph_strut_solo, 2, 2
	song ph_cure_blend, 2, 2
	song ph_cure_held, 2, 2
	song ph_cure_solo, 2, 2
	song ph_nurse_blend, 2, 2
	song ph_nurse_held, 2, 2
	song ph_nurse_solo, 2, 2
	song mus_littleroot_test, 0, 0
	song mus_gsc_route38, 0, 0
	song mus_caught, 0, 0
	song mus_victory_wild, 0, 0
	song mus_victory_gym_leader, 0, 0
	song mus_victory_league, 0, 0
	song mus_c_comm_center, 0, 0
	song mus_gsc_pewter, 0, 0
	song mus_c_vs_legend_beast, 0, 0
	song mus_route101, 0, 0
	song mus_route110, 0, 0
	song mus_route120, 0, 0
	song mus_petalburg, 0, 0
	song mus_oldale, 0, 0
	song mus_gym, 0, 0
	song mus_surf, 0, 0
	song mus_petalburg_woods, 0, 0
	song mus_level_up, 2, 2
	song mus_heal, 2, 2
	song mus_obtain_badge, 2, 2
	song mus_obtain_item, 2, 2
	song mus_evolved, 2, 2
	song mus_obtain_tmhm, 2, 2
	song mus_lilycove_museum, 0, 0
	song mus_route122, 0, 0
	song mus_oceanic_museum, 0, 0
	song mus_evolution_intro, 2, 2
	song mus_evolution, 0, 0
	song mus_move_deleted, 2, 2
	song mus_encounter_girl, 0, 0
	song mus_encounter_male, 0, 0
	song mus_abandoned_ship, 0, 0
	song mus_fortree, 0, 0
	song mus_birch_lab, 0, 0
	song mus_b_tower_rs, 0, 0
	song mus_encounter_swimmer, 0, 0
	song mus_cave_of_origin, 0, 0
	song mus_obtain_berry, 2, 2
	song mus_awaken_legend, 2, 2
	song mus_slots_jackpot, 2, 2
	song mus_slots_win, 2, 2
	song mus_too_bad, 2, 2
	song mus_roulette, 0, 0
	song mus_link_contest_p1, 0, 0
	song mus_link_contest_p2, 0, 0
	song mus_link_contest_p3, 0, 0
	song mus_link_contest_p4, 0, 0
	song mus_encounter_rich, 0, 0
	song mus_verdanturf, 0, 0
	song mus_rustboro, 0, 0
	song mus_poke_center, 0, 0
	song mus_route104, 0, 0
	song mus_route119, 0, 0
	song mus_cycling, 0, 0
	song mus_poke_mart, 0, 0
	song mus_littleroot, 0, 0
	song mus_mt_chimney, 0, 0
	song mus_encounter_female, 0, 0
	song mus_lilycove, 0, 0
	song mus_route111, 0, 0
	song mus_help, 0, 0
	song mus_underwater, 0, 0
	song mus_victory_trainer, 0, 0
	song mus_title, 0, 0
	song mus_intro, 0, 0
	song mus_encounter_may, 0, 0
	song mus_encounter_intense, 0, 0
	song mus_encounter_cool, 0, 0
	song mus_route113, 0, 0
	song mus_encounter_aqua, 0, 0
	song mus_follow_me, 0, 0
	song mus_encounter_brendan, 0, 0
	song mus_ever_grande, 0, 0
	song mus_encounter_suspicious, 0, 0
	song mus_victory_aqua_magma, 0, 0
	song mus_cable_car, 0, 0
	song mus_game_corner, 0, 0
	song mus_dewford, 0, 0
	song mus_safari_zone, 0, 0
	song mus_victory_road, 0, 0
	song mus_aqua_magma_hideout, 0, 0
	song mus_sailing, 0, 0
	song mus_mt_pyre, 0, 0
	song mus_slateport, 0, 0
	song mus_mt_pyre_exterior, 0, 0
	song mus_school, 0, 0
	song mus_hall_of_fame, 0, 0
	song mus_fallarbor, 0, 0
	song mus_sealed_chamber, 0, 0
	song mus_contest_winner, 0, 0
	song mus_contest, 0, 0
	song mus_encounter_magma, 0, 0
	song mus_intro_battle, 0, 0
	song mus_weather_kyogre, 0, 0
	song mus_weather_groudon, 0, 0
	song mus_sootopolis, 0, 0
	song mus_contest_results, 0, 0
	song mus_hall_of_fame_room, 0, 0
	song mus_trick_house, 0, 0
	song mus_encounter_twins, 0, 0
	song mus_encounter_elite_four, 0, 0
	song mus_encounter_hiker, 0, 0
	song mus_contest_lobby, 0, 0
	song mus_encounter_interviewer, 0, 0
	song mus_encounter_champion, 0, 0
	song mus_credits, 0, 0
	song mus_end, 0, 0
	song mus_vs_wild, 0, 0
	song mus_vs_aqua_magma, 0, 0
	song mus_vs_trainer, 0, 0
	song mus_vs_gym_leader, 0, 0
	song mus_vs_champion, 0, 0
	song mus_vs_regi, 0, 0
	song mus_vs_kyogre_groudon, 0, 0
	song mus_vs_rival, 0, 0
	song mus_vs_elite_four, 0, 0
	song mus_vs_aqua_magma_leader, 0, 0
	song mus_rg_follow_me, 0, 0
	song mus_rg_game_corner, 0, 0
	song mus_rg_rocket_hideout, 0, 0
	song mus_rg_gym, 0, 0
	song mus_rg_jigglypuff, 2, 2
	song mus_rg_intro_fight, 0, 0
	song mus_rg_title, 0, 0
	song mus_rg_cinnabar, 0, 0
	song mus_rg_lavender, 0, 0
	song mus_rg_heal, 0, 0
	song mus_rg_cycling, 0, 0
	song mus_rg_encounter_rocket, 0, 0
	song mus_rg_encounter_girl, 0, 0
	song mus_rg_encounter_boy, 0, 0
	song mus_rg_hall_of_fame, 0, 0
	song mus_rg_viridian_forest, 0, 0
	song mus_rg_mt_moon, 0, 0
	song mus_rg_poke_mansion, 0, 0
	song mus_rg_credits, 0, 0
	song mus_rg_route1, 0, 0
	song mus_rg_route24, 0, 0
	song mus_rg_route3, 0, 0
	song mus_rg_route11, 0, 0
	song mus_rg_victory_road, 0, 0
	song mus_rg_vs_gym_leader, 0, 0
	song mus_rg_vs_trainer, 0, 0
	song mus_rg_vs_wild, 0, 0
	song mus_rg_vs_champion, 0, 0
	song mus_rg_pallet, 0, 0
	song mus_rg_oak_lab, 0, 0
	song mus_rg_oak, 0, 0
	song mus_rg_poke_center, 0, 0
	song mus_rg_ss_anne, 0, 0
	song mus_rg_surf, 0, 0
	song mus_rg_poke_tower, 0, 0
	song mus_rg_silph, 0, 0
	song mus_rg_fuchsia, 0, 0
	song mus_rg_celadon, 0, 0
	song mus_victory_trainer, 0, 0
	song mus_victory_wild, 0, 0
	song mus_victory_gym_leader, 0, 0
	song mus_rg_vermilion, 0, 0
	song mus_rg_pewter, 0, 0
	song mus_rg_encounter_rival, 0, 0
	song mus_rg_rival_exit, 0, 0
	song mus_rg_dex_rating, 2, 2
	song mus_rg_obtain_key_item, 2, 2
	song mus_rg_caught_intro, 2, 2
	song mus_rg_photo, 2, 2
	song mus_rg_game_freak, 0, 0
	song mus_rg_caught, 0, 0
	song mus_rg_new_game_instruct, 0, 0
	song mus_rg_new_game_intro, 0, 0
	song mus_rg_new_game_exit, 0, 0
	song mus_rg_poke_jump, 0, 0
	song mus_rg_union_room, 0, 0
	song mus_rg_net_center, 0, 0
	song mus_rg_mystery_gift, 0, 0
	song mus_rg_berry_pick, 0, 0
	song mus_rg_mt_moon, 0, 0
	song mus_rg_follow_me, 0, 0
	song mus_rg_sevii_route, 0, 0
	song mus_rg_viridian_forest, 0, 0
	song mus_rg_pewter, 0, 0
	song mus_rg_sevii_45, 0, 0
	song mus_rg_sevii_67, 0, 0
	song mus_rg_poke_flute, 2, 2
	song mus_rg_vs_deoxys, 0, 0
	song mus_rg_vs_mewtwo, 0, 0
	song mus_rg_vs_legend, 0, 0
	song mus_rg_encounter_gym_leader, 0, 0
	song mus_rg_encounter_deoxys, 0, 0
	song mus_rg_trainer_tower, 0, 0
	song mus_rg_slow_pallet, 0, 0
	song mus_rg_teachy_tv_menu, 0, 0
	song mus_abnormal_weather, 0, 0
	song mus_b_frontier, 0, 0
	song mus_b_arena, 0, 0
	song mus_obtain_b_points, 2, 2
	song mus_register_match_call, 2, 2
	song mus_b_pyramid, 0, 0
	song mus_b_pyramid_top, 0, 0
	song mus_b_palace, 0, 0
	song mus_rayquaza_appears, 0, 0
	song mus_b_tower, 0, 0
	song mus_obtain_symbol, 2, 2
	song mus_b_dome, 0, 0
	song mus_b_pike, 0, 0
	song mus_b_factory, 0, 0
	song mus_vs_kyogre_groudon, 0, 0
	song mus_vs_frontier_brain, 0, 0
	song mus_vs_mew, 0, 0
	song mus_b_dome_lobby, 0, 0
	song mus_dp_twinleaf_day, 0, 0
	song mus_dp_sandgem_day, 0, 0
	song mus_dp_floaroma_day, 0, 0
	song mus_dp_solaceon_day, 0, 0
	song mus_dp_route225_day, 0, 0
	song mus_dp_valor_lakefront_day, 0, 0
	song mus_dp_jubilife_day, 0, 0
	song mus_dp_canalave_day, 0, 0
	song mus_dp_oreburgh_day, 0, 0
	song mus_dp_eterna_day, 0, 0
	song mus_dp_hearthome_day, 0, 0
	song mus_dp_veilstone_day, 0, 0
	song mus_dp_sunyshore_day, 0, 0
	song mus_dp_snowpoint_day, 0, 0
	song mus_dp_pokemon_league_day, 0, 0
	song mus_dp_fight_area_day, 0, 0
	song mus_dp_route201_day, 0, 0
	song mus_dp_route203_day, 0, 0
	song mus_dp_route205_day, 0, 0
	song mus_dp_route206_day, 0, 0
	song mus_dp_route209_day, 0, 0
	song mus_dp_route210_day, 0, 0
	song mus_dp_route216_day, 0, 0
	song mus_dp_route228_day, 0, 0
	song mus_dp_rowan, 0, 0
	song mus_dp_tv_broadcast, 0, 0
	song mus_dp_twinleaf_night, 0, 0
	song mus_dp_sandgem_night, 0, 0
	song mus_dp_floaroma_night, 0, 0
	song mus_dp_solaceon_night, 0, 0
	song mus_dp_route225_night, 0, 0
	song mus_dp_valor_lakefront_night, 0, 0
	song mus_dp_jubilife_night, 0, 0
	song mus_dp_canalave_night, 0, 0
	song mus_dp_oreburgh_night, 0, 0
	song mus_dp_eterna_night, 0, 0
	song mus_dp_hearthome_night, 0, 0
	song mus_dp_veilstone_night, 0, 0
	song mus_dp_sunyshore_night, 0, 0
	song mus_dp_snowpoint_night, 0, 0
	song mus_dp_pokemon_league_night, 0, 0
	song mus_dp_fight_area_night, 0, 0
	song mus_dp_route201_night, 0, 0
	song mus_dp_route203_night, 0, 0
	song mus_dp_route205_night, 0, 0
	song mus_dp_route206_night, 0, 0
	song mus_dp_route209_night, 0, 0
	song mus_dp_route210_night, 0, 0
	song mus_dp_route216_night, 0, 0
	song mus_dp_route228_night, 0, 0
	song mus_dp_underground, 0, 0
	song mus_dp_flag_captured, 0, 0
	song mus_dp_victory_road, 0, 0
	song mus_dp_eterna_forest, 0, 0
	song mus_dp_old_chateau, 0, 0
	song mus_dp_lake_caverns, 0, 0
	song mus_dp_amity_square, 0, 0
	song mus_dp_galactic_hq, 0, 0
	song mus_dp_galactic_eterna_building, 0, 0
	song mus_dp_great_marsh, 0, 0
	song mus_dp_lake, 0, 0
	song mus_dp_mt_coronet, 0, 0
	song mus_dp_spear_pillar, 0, 0
	song mus_dp_stark_mountain, 0, 0
	song mus_dp_oreburgh_gate, 0, 0
	song mus_dp_oreburgh_mine, 0, 0
	song mus_dp_inside_pokemon_league, 0, 0
	song mus_dp_hall_of_fame_room, 0, 0
	song mus_dp_poke_center_day, 0, 0
	song mus_dp_poke_center_night, 0, 0
	song mus_dp_gym, 0, 0
	song mus_dp_rowan_lab, 0, 0
	song mus_dp_contest_lobby, 0, 0
	song mus_dp_poke_mart, 0, 0
	song mus_dp_game_corner, 0, 0
	song mus_dp_b_tower, 0, 0
	song mus_dp_tv_station, 0, 0
	song mus_dp_galactic_hq_basement, 0, 0
	song mus_dp_azure_flute, 0, 0
	song mus_dp_hall_of_origin, 0, 0
	song mus_dp_gts, 0, 0
	song mus_dp_encounter_boy, 0, 0
	song mus_dp_encounter_twins, 0, 0
	song mus_dp_encounter_intense, 0, 0
	song mus_dp_encounter_galactic, 0, 0
	song mus_dp_encounter_lady, 0, 0
	song mus_dp_encounter_hiker, 0, 0
	song mus_dp_encounter_rich, 0, 0
	song mus_dp_encounter_sailor, 0, 0
	song mus_dp_encounter_suspicious, 0, 0
	song mus_dp_encounter_ace_trainer, 0, 0
	song mus_dp_encounter_girl, 0, 0
	song mus_dp_encounter_cyclist, 0, 0
	song mus_dp_encounter_artist, 0, 0
	song mus_dp_encounter_elite_four, 0, 0
	song mus_dp_encounter_champion, 0, 0
	song mus_dp_vs_wild, 0, 0
	song mus_dp_vs_gym_leader, 0, 0
	song mus_dp_vs_uxie_mesprit_azelf, 0, 0
	song mus_dp_vs_trainer, 0, 0
	song mus_dp_vs_galactic_boss, 0, 0
	song mus_dp_vs_dialga_palkia, 0, 0
	song mus_dp_vs_champion, 0, 0
	song mus_dp_vs_galactic, 0, 0
	song mus_dp_vs_rival, 0, 0
	song mus_dp_vs_arceus, 0, 0
	song mus_dp_vs_legend, 0, 0
	song mus_dp_victory_wild, 0, 0
	song mus_dp_victory_trainer, 0, 0
	song mus_dp_victory_gym_leader, 0, 0
	song mus_dp_victory_champion, 0, 0
	song mus_dp_victory_galactic, 0, 0
	song mus_dp_victory_elite_four, 0, 0
	song mus_dp_vs_galactic_commander, 0, 0
	song mus_dp_contest, 0, 0
	song mus_dp_vs_elite_four, 0, 0
	song mus_dp_follow_me, 0, 0
	song mus_dp_rival, 0, 0
	song mus_dp_lake_event, 0, 0
	song mus_dp_evolution, 0, 0
	song mus_dp_lucas, 0, 0
	song mus_dp_dawn, 0, 0
	song mus_dp_legend_appears, 0, 0
	song mus_dp_catastrophe, 0, 0
	song mus_dp_poke_radar, 0, 0
	song mus_dp_surf, 0, 0
	song mus_dp_cycling, 0, 0
	song mus_dp_lets_go_together, 2, 2
	song mus_dp_tv_end, 2, 2
	song mus_dp_level_up, 2, 2
	song mus_dp_evolved, 2, 2
	song mus_dp_obtain_key_item, 2, 2
	song mus_dp_obtain_item, 2, 2
	song mus_dp_caught_intro, 2, 2
	song mus_dp_dex_rating, 2, 2
	song mus_dp_obtain_badge, 2, 2
	song mus_dp_poketch, 2, 2
	song mus_dp_obtain_tmhm, 2, 2
	song mus_dp_obtain_accessory, 2, 2
	song mus_dp_move_deleted, 2, 2
	song mus_dp_heal, 2, 2
	song mus_dp_obtain_berry, 2, 2
	song mus_dp_contest_dress_up, 0, 0
	song mus_dp_hall_of_fame, 0, 0
	song mus_dp_intro, 0, 0
	song mus_dp_title, 0, 0
	song mus_dp_mystery_gift, 0, 0
	song mus_dp_wfc, 0, 0
	song mus_dp_dance_easy, 0, 0
	song mus_dp_dance_difficult, 0, 0
	song mus_dp_contest_results, 0, 0
	song mus_dp_contest_winner, 0, 0
	song mus_dp_poffins, 0, 0
	song mus_dp_slots_win, 0, 0
	song mus_dp_slots_jackpot, 0, 0
	song mus_dp_credits, 0, 0
	song mus_dp_slots_unused, 0, 0
	song mus_pl_fight_area_day, 0, 0
	song mus_pl_tv_broadcast, 0, 0
	song mus_pl_tv_end, 2, 2
	song mus_pl_intro, 0, 0
	song mus_pl_title, 0, 0
	song mus_pl_distortion_world, 0, 0
	song mus_pl_b_arcade, 0, 0
	song mus_pl_b_hall, 0, 0
	song mus_pl_b_castle, 0, 0
	song mus_pl_b_factory, 0, 0
	song mus_pl_global_terminal, 0, 0
	song mus_pl_lilycove_bossa_nova, 0, 0
	song mus_pl_looker, 0, 0
	song mus_pl_vs_giratina, 0, 0
	song mus_pl_vs_frontier_brain, 0, 0
	song mus_pl_victory_frontier_brain, 0, 0
	song mus_pl_vs_regi, 0, 0
	song mus_pl_contest_cool, 0, 0
	song mus_pl_contest_smart, 0, 0
	song mus_pl_contest_cute, 0, 0
	song mus_pl_contest_tough, 0, 0
	song mus_pl_contest_beauty, 0, 0
	song mus_pl_spin_trade, 0, 0
	song mus_pl_wifi_minigames, 0, 0
	song mus_pl_wifi_plaza, 0, 0
	song mus_pl_wifi_parade, 0, 0
	song mus_pl_giratina_appears_1, 0, 0
	song mus_pl_giratina_appears_2, 0, 0
	song mus_pl_mystery_gift, 0, 0
	song mus_pl_twinleaf_music_box, 0, 0
	song mus_pl_obtain_arcade_points, 2, 2
	song mus_pl_obtain_castle_points, 2, 2
	song mus_pl_obtain_b_points, 2, 2
	song mus_pl_win_minigame, 2, 2
	song mus_hg_intro, 0, 0
	song mus_hg_title, 0, 0
	song mus_hg_new_game, 0, 0
	song mus_hg_evolution, 0, 0
	song mus_hg_evolution_no_intro, 0, 0
	song mus_hg_cycling, 0, 0
	song mus_hg_surf, 0, 0
	song mus_hg_hall_of_fame, 0, 0
	song mus_hg_credits, 0, 0
	song mus_hg_end, 0, 0
	song mus_hg_new_bark, 0, 0
	song mus_hg_cherrygrove, 0, 0
	song mus_hg_violet, 0, 0
	song mus_hg_azalea, 0, 0
	song mus_hg_goldenrod, 0, 0
	song mus_hg_ecruteak, 0, 0
	song mus_hg_cianwood, 0, 0
	song mus_hg_route29, 0, 0
	song mus_hg_route30, 0, 0
	song mus_hg_route34, 0, 0
	song mus_hg_route38, 0, 0
	song mus_hg_route42, 0, 0
	song mus_hg_vermilion, 0, 0
	song mus_hg_pewter, 0, 0
	song mus_hg_cerulean, 0, 0
	song mus_hg_lavender, 0, 0
	song mus_hg_celadon, 0, 0
	song mus_hg_pallet, 0, 0
	song mus_hg_cinnabar, 0, 0
	song mus_hg_route1, 0, 0
	song mus_hg_route3, 0, 0
	song mus_hg_route11, 0, 0
	song mus_hg_route24, 0, 0
	song mus_hg_route26, 0, 0
	song mus_hg_poke_center, 0, 0
    song mus_hg_poke_mart, 0, 0
	song mus_hg_gym, 0, 0
	song mus_hg_elm_lab, 0, 0
	song mus_hg_oak, 0, 0
	song mus_hg_dance_theater, 0, 0
    song mus_hg_game_corner, 0, 0
	song mus_hg_b_tower, 0, 0
	song mus_hg_b_tower_reception, 0, 0
	song mus_hg_sprout_tower, 0, 0
    song mus_hg_union_cave, 0, 0
    song mus_hg_ruins_of_alph, 0, 0
	song mus_hg_national_park, 0, 0
	song mus_hg_burned_tower, 0, 0
	song mus_hg_bell_tower, 0, 0
	song mus_hg_lighthouse, 0, 0
	song mus_hg_team_rocket_hq, 0, 0
	song mus_hg_ice_path, 0, 0
	song mus_hg_dragons_den, 0, 0
	song mus_hg_rock_tunnel, 0, 0
	song mus_hg_viridian_forest, 0, 0
	song mus_hg_victory_road, 0, 0
	song mus_hg_pokemon_league, 0, 0
	song mus_hg_follow_me_1, 0, 0
	song mus_hg_follow_me_2, 0, 0
	song mus_hg_encounter_rival, 0, 0
	song mus_hg_rival_exit, 0, 0
	song mus_hg_bug_contest_prep, 0, 0
	song mus_hg_bug_catching_contest, 0, 0
	song mus_hg_radio_rocket, 0, 0
	song mus_hg_rocket_takeover, 0, 0
	song mus_hg_magnet_train, 0, 0
	song mus_hg_ss_aqua, 0, 0
	song mus_hg_mt_moon_square, 0, 0
    song mus_hg_radio_jingle, 0, 0
	song mus_hg_radio_lullaby, 0, 0
	song mus_hg_radio_march, 0, 0
	song mus_hg_radio_unown, 0, 0
	song mus_hg_radio_poke_flute, 0, 0
	song mus_hg_radio_oak, 0, 0
    song mus_hg_radio_buena, 0, 0
	song mus_hg_eusine, 0, 0
	song mus_hg_clair, 0, 0
	song mus_hg_encounter_girl_1, 0, 0
	song mus_hg_encounter_boy_1, 0, 0
	song mus_hg_encounter_suspicious_1, 0, 0
	song mus_hg_encounter_sage, 0, 0
	song mus_hg_encounter_kimono_girl, 0, 0
	song mus_hg_encounter_rocket, 0, 0
	song mus_hg_encounter_girl_2, 0, 0
	song mus_hg_encounter_boy_2, 0, 0
	song mus_hg_encounter_suspicious_2, 0, 0
	song mus_hg_vs_wild, 0, 0
	song mus_hg_vs_trainer, 0, 0
	song mus_hg_vs_gym_leader, 0, 0
	song mus_hg_vs_rival, 0, 0
	song mus_hg_vs_rocket, 0, 0
	song mus_hg_vs_suicune, 0, 0
	song mus_hg_vs_entei, 0, 0
	song mus_hg_vs_raikou, 0, 0
	song mus_hg_vs_champion, 0, 0
	song mus_hg_vs_wild_kanto, 0, 0
	song mus_hg_vs_trainer_kanto, 0, 0
	song mus_hg_vs_gym_leader_kanto, 0, 0
	song mus_hg_victory_trainer, 0, 0
	song mus_hg_victory_wild, 0, 0
	song mus_hg_caught, 0, 0
	song mus_hg_victory_gym_leader, 0, 0
	song mus_hg_vs_ho_oh, 0, 0
	song mus_hg_vs_lugia, 0, 0
	song mus_hg_pokeathlon_lobby, 0, 0
	song mus_hg_pokeathlon_start, 0, 0
	song mus_hg_pokeathlon_before, 0, 0
	song mus_hg_pokeathlon_event, 0, 0
	song mus_hg_pokeathlon_finals, 0, 0
	song mus_hg_pokeathlon_results, 0, 0
	song mus_hg_pokeathlon_end, 0, 0
	song mus_hg_pokeathlon_winner, 0, 0
	song mus_hg_b_factory, 0, 0
	song mus_hg_b_hall, 0, 0
	song mus_hg_b_arcade, 0, 0
	song mus_hg_b_castle, 0, 0
	song mus_hg_vs_frontier_brain, 0, 0
	song mus_hg_victory_frontier_brain, 0, 0
	song mus_hg_wfc, 0, 0
	song mus_hg_mystery_gift, 0, 0
	song mus_hg_wifi_plaza, 0, 0
	song mus_hg_wifi_minigames, 0, 0
	song mus_hg_wifi_parade, 0, 0
	song mus_hg_global_terminal, 0, 0
	song mus_hg_spin_trade, 0, 0
	song mus_hg_gts, 0, 0
	song mus_hg_route47, 0, 0
	song mus_hg_safari_zone_gate, 0, 0
	song mus_hg_safari_zone, 0, 0
	song mus_hg_ethan, 0, 0
	song mus_hg_lyra, 0, 0
    song mus_hg_game_corner_win, 0, 0
	song mus_hg_kimono_girl_dance, 0, 0
    song mus_hg_kimono_girl, 0, 0
	song mus_hg_ho_oh_appears, 0, 0
	song mus_hg_lugia_appears, 0, 0
	song mus_hg_spiky_eared_pichu, 0, 0
	song mus_hg_sinjou_ruins, 0, 0
	song mus_hg_radio_route101, 0, 0
	song mus_hg_radio_route201, 0, 0
	song mus_hg_radio_trainer, 0, 0
	song mus_hg_radio_variety, 0, 0
	song mus_hg_vs_kyogre_groudon, 0, 0
	song mus_hg_pokewalker, 0, 0
	song mus_hg_vs_arceus, 0, 0
	song mus_hg_heal, 2, 2
	song mus_hg_level_up, 2, 2
    song mus_hg_obtain_item, 2, 2
	song mus_hg_obtain_key_item, 2, 2
	song mus_hg_evolved, 2, 2
	song mus_hg_obtain_badge, 2, 2
    song mus_hg_obtain_tmhm, 2, 2
	song mus_hg_obtain_accessory, 2, 2
	song mus_hg_move_deleted, 2, 2
	song mus_hg_obtain_berry, 2, 2
	song mus_hg_dex_rating_1, 2, 2
	song mus_hg_dex_rating_2, 2, 2
	song mus_hg_dex_rating_3, 2, 2
	song mus_hg_dex_rating_4, 2, 2
	song mus_hg_dex_rating_5, 2, 2
	song mus_hg_dex_rating_6, 2, 2
    song mus_hg_obtain_egg, 2, 2
	song mus_hg_bug_contest_1st_place, 2, 2
	song mus_hg_bug_contest_2nd_place, 2, 2
	song mus_hg_bug_contest_3rd_place, 2, 2
	song mus_hg_card_flip, 2, 2 @ TODO: Voltorb Flip
	song mus_hg_card_flip_game_over, 2, 2 @ TODO: Voltorb Flip
	song mus_hg_pokegear_registered, 2, 2 @ TODO: Pokegear
	song mus_hg_lets_go_together, 2, 2
	song mus_hg_pokeathlon_ready, 2, 2
	song mus_hg_pokeathlon_1st_place, 2, 2
	song mus_hg_receive_pokemon, 2, 2
	song mus_hg_obtain_arcade_points, 2, 2
	song mus_hg_obtain_castle_points, 2, 2
	song mus_hg_obtain_b_points, 2, 2
	song mus_hg_win_minigame, 2, 2

	.align 2
dummy_song_header:
	.byte 0, 0, 0, 0

	.align 2
gGBSSongTable:: @ "gbs_hg_" tracks are new tracks that were transcribed from HGSS instead of being from Crystal.
	
	song_gbs SE_SELECT, gbs_sfx_readtext_Header, 2, 2

	@ Fanfares (src/sound.c)
	song_gbs MUS_LEVEL_UP, gbs_sfx_levelup_Header, 2, 2	@ Used for more than just Leveling Up TODO: Pinpoint
	song_gbs MUS_EVOLVED, gbs_sfx_caughtmon_Header, 2, 2	@ Finish Evolving/Hatching & Pokémon Caught (Fanfare mapped to HGSS Version) TODO: Test
	song_gbs MUS_OBTAIN_SYMBOL, gbs_sfx_getbadge_Header, 2, 2	@ Obtain Symbol Fanfare TODO: GBS CONVERSION

	song_gbs MUS_HEAL, gbs_healpokemon_Header, 2, 2	@ Healing & Goldenrod Haircuts Fanfare -> Techically didn't need to be mapped due to how fanfares are handled
	song_gbs MUS_OBTAIN_BADGE, gbs_sfx_getbadge_Header, 2, 2	@ Obtain Gym Badge Fanfare -> Techically didn't need to be mapped due to how fanfares are handled
	song_gbs MUS_OBTAIN_ITEM, gbs_sfx_item_Header, 2, 2	@ Obtain Item Fanfare -> Techically didn't need to be mapped due to how fanfares are handled
	song_gbs MUS_OBTAIN_TMHM, gbs_sfx_gettm_Header, 2, 2	@ Obtain TMHM Fanfare -> Techically didn't need to be mapped due to how fanfares are handled
	song_gbs MUS_OBTAIN_BERRY, gbs_sfx_item_Header, 2, 2	@ Obtain Berry Fanfare -> Techically didn't need to be mapped due to how fanfares are handled
	song_gbs MUS_OBTAIN_B_POINTS, gbs_sfx_getcoin_Header, 2, 2	@ Obtain Battle Points Fanfare -> Techically didn't need to be mapped due to how fanfares are handled
	song_gbs MUS_REGISTER_MATCH_CALL, gbs_sfx_registerphonenumber_Header, 2, 2	@ PokéNav Phone Number Registered Fanfare -> Techically didn't need to be mapped due to how fanfares are handled

	song_gbs MUS_HG_LEVEL_UP, gbs_sfx_levelup_Header, 2, 2 @ Music that gets played when `playfanfare MUS_LEVEL_UP` is called
	song_gbs MUS_HG_HEAL, gbs_healpokemon_Header, 2, 2 @ Music that gets played when `playfanfare MUS_HEAL` is called 
	song_gbs MUS_HG_OBTAIN_ITEM, gbs_sfx_item_Header, 2, 2 @ Music that gets played when `playfanfare MUS_OBTAIN_ITEM` is called
	song_gbs MUS_HG_OBTAIN_KEY_ITEM, gbs_sfx_keyitem_Header, 2, 2 @ Music that gets played when `playfanfare MUS_RG_OBTAIN_KEY_ITEM` is called
	song_gbs MUS_HG_EVOLVED, gbs_sfx_caughtmon_Header, 2, 2	@ Music that gets played when `playfanfare MUS_EVOLVED` is called & when catching a Pokémon
	song_gbs MUS_HG_OBTAIN_BADGE, gbs_sfx_getbadge_Header, 2, 2 @ Music that gets played when `playfanfare MUS_OBTAIN_BADGE` is called
	song_gbs MUS_HG_OBTAIN_TMHM, gbs_sfx_gettm_Header, 2, 2 @ Music that gets played when `playfanfare MUS_OBTAIN_TMHM` is called
	song_gbs MUS_HG_OBTAIN_BERRY, gbs_sfx_item_Header, 2, 2 @ Music that gets played when `playfanfare MUS_OBTAIN_BERRY` is called TODO: GBS CONVERSION
	song_gbs MUS_HG_OBTAIN_EGG, gbs_sfx_getegg_Header, 2, 2 @ Music played when receiving an egg from the Day Care (not Odd Egg)
	song_gbs MUS_HG_POKEGEAR_REGISTERED, gbs_sfx_registerphonenumber_Header, 2, 2 @ Music that gets played when `playfanfare MUS_REGISTER_MATCH_CALL` is called
	song_gbs MUS_HG_BUG_CONTEST_1ST_PLACE, gbs_sfx_1stplace_Header, 2, 2 @ Music played when first place is announced in Bug Catching Contest
	song_gbs MUS_HG_BUG_CONTEST_2ND_PLACE, gbs_sfx_2ndplace_Header, 2, 2 @ Music played when second place is announced in Bug Catching Contest
	song_gbs MUS_HG_BUG_CONTEST_3RD_PLACE, gbs_sfx_3rdplace_Header, 2, 2 @ Music played when third place is announced in Bug Catching Contest
	song_gbs MUS_HG_OBTAIN_B_POINTS, gbs_sfx_item_Header, 2, 2 @ @ Music that gets played when `playfanfare MUS_OBTAIN_B_POINTS` is called
	@song_gbs MUS_HG_OBTAIN_ACCESSORY, 2, 2 @ Unused in HnS
	@song_gbs MUS_HG_OBTAIN_ARCADE_POINTS, 2, 2 @ Unused in HnS
	@song_gbs MUS_HG_OBTAIN_CASTLE_POINTS, 2, 2 @ Unused in HnS

	@ ---------------------------------- @

	@ Intro
	song_gbs MUS_HG_INTRO, gbs_goldsilveropening_Header, 0, 0 @ Game Intro BGM
	song_gbs MUS_HG_TITLE, gbs_titlescreen_Header, 0, 0 @ Game Title Screen BGM
	song_gbs MUS_HG_NEW_GAME, gbs_mainmenu_Header, 0, 0	@ Oak's Intro Speech BGM

	@ ---------------------------------- @

	@ Hall of Fame / Credits
	song_gbs MUS_HG_HALL_OF_FAME, gbs_halloffame_Header, 0, 0	@ Hall of Fame Room BGM & Party Hall of Fame slideshow
	song_gbs MUS_HG_CREDITS, gbs_credits_Header, 0, 0		@ Credits BGM
	song_gbs MUS_HG_END, gbs_hg_end_Header, 0, 0 @ End of Credits BGM
	
	@ ---------------------------------- @

	@ Towns/Cities
	song_gbs MUS_HG_NEW_BARK, gbs_newbarktown_Header, 0, 0 @ New Bark Town/Houses BGM & Indigo Plateau Teleport Guy
	song_gbs MUS_HG_CHERRYGROVE, gbs_cherrygrovecity_Header, 0, 0	@ Cherrygrove City + Houses & Mahogany Town + Buildings BGM
	song_gbs MUS_HG_VIOLET, gbs_violetcity_Header, 0, 0	@ Olivine City & Violet City BGM
	song_gbs MUS_HG_AZALEA, gbs_azaleatown_Header, 0, 0	@ Azalea Town/Houses & Blackthorn City/Houses BGM
	song_gbs MUS_HG_GOLDENROD, gbs_goldenrodcity_Header, 0, 0	@ Goldenrod City & Houses/Buildings BGM
	song_gbs MUS_HG_ECRUTEAK, gbs_ecruteakcity_Header, 0, 0	@ Ecruteak City & Houses BGM @ TODO: HGSS normal Ecruteak is a new track, the GB Sounds item uses Crystal's music for the town
	song_gbs MUS_HG_CIANWOOD, gbs_ecruteakcity_Header, 0, 0	@ Cianwood City & Houses BGM
	song_gbs MUS_HG_VERMILION, gbs_vermilioncity_Header, 0, 0	@ Vermilion City/Houses/Port BGM
	song_gbs MUS_HG_PEWTER, gbs_viridiancity_Header, 0, 0	@ Pewter City/Buildings, Saffron City/Buildings, Viridian City/Houses, Power Plant BGM
	song_gbs MUS_HG_CERULEAN, gbs_hg_cerulean_Header, 0, 0	@ Cerulean City/Buildings & Fuchsia City/Houses BGM
	song_gbs MUS_HG_LAVENDER, gbs_lavendertown_Header, 0, 0	@ Lavender Town/Buildings BGM
	song_gbs MUS_HG_CELADON, gbs_celadoncity_Header, 0, 0		@ Celadon City/Buildings (Not Department Store) BGM
	song_gbs MUS_HG_PALLET, gbs_pallettown_Header, 0, 0	@ Pallet Town/Houses BGM
	song_gbs MUS_HG_CINNABAR, gbs_hg_cinnabar_Header, 0, 0	@ Cinnabar Island BGM
	
	@ ---------------------------------- @

	@ Routes
	song_gbs MUS_HG_ROUTE1, gbs_route1_Header, 0, 0	@ Route 1 (R1) BGM
	song_gbs MUS_HG_ROUTE3, gbs_route3_Header, 0, 0, @ R2-10 + Houses/Gates, R16 + House/Gate, R18-20 + Gates BGM
	song_gbs MUS_HG_ROUTE11, gbs_route12_Header, 0, 0	@ R11-15 + House/Gate BGM
	song_gbs MUS_HG_ROUTE24, gbs_hg_route24_Header, 0, 0	@ R24 & R25 + Bill's House BGM
	song_gbs MUS_HG_ROUTE26, gbs_route26_Header, 0, 0	@ R26-28 + Houses & Pokémon League Reception Gate
	song_gbs MUS_HG_ROUTE29, gbs_route29_Header, 0, 0	@ R29 & R29 Gate BGM
	song_gbs MUS_HG_ROUTE30, gbs_route30_Header, 0, 0	@ R30, R31, R32, R33, R30 Houses, R31 Gate, R32 Gate BGM
	song_gbs MUS_HG_ROUTE34, gbs_route36_Header, 0, 0	@ R34, R34 Gate, R34 Daycare, R35, R35 Gate, R36, R36 Gate, R37, R40, R40 Gate, R41, R45, R46, Azalea-Ilex Gate, National Park Gate BGM
	song_gbs MUS_HG_ROUTE38, gbs_route37_Header, 0, 0	@ R38, R38 Gate, R39, R39 Barn/Farm House BGM
	song_gbs MUS_HG_ROUTE42, gbs_lakeofrage_Header, 0, 0	@ R42, R42 Gate, R43, R43 Gates, R44, Lake of Rage + Houses BGM
	song_gbs MUS_HG_ROUTE47, gbs_hg_route47_Header, 0, 0	@ R47, R48, Cliff Edge Cave & Gate, & Embedded Tower
	
	@ ---------------------------------- @

	@ Battle Frontier
	@song_gbs MUS_LILYCOVE_MUSEUM, gbs_TODO:_Header, 0, 0	@ Location - Battle Frontier Ranking Hall TODO: GBS CONVERSION
	song_gbs MUS_B_TOWER_RS, gbs_battletowerlobby_Header, 0, 0	@ Battle Frontier Lounges, Exchange, Reception, Scotts House BGM TODO: GBS CONVERSION
	song_gbs MUS_B_FRONTIER, gbs_battletowertheme_Header, 0, 0 @ Battle Frontier Outside East/West BGM TODO: GBS CONVERSION
	song_gbs MUS_B_ARENA, gbs_battletowertheme_Header, 0, 0	@ Battle Arena BGM TODO: GBS CONVERSION
	song_gbs MUS_B_PYRAMID_TOP, gbs_battletowertheme_Header, 0, 0	@ Battle Pyramid Top Floor BGM (Script triggered) TODO: GBS CONVERSION
	song_gbs MUS_B_PYRAMID, gbs_battletowertheme_Header, 0, 0	@ Battle Pyramid Lobby & Floor (Script triggered) TODO: GBS CONVERSION
	song_gbs MUS_B_PALACE, gbs_battletowertheme_Header, 0, 0	@ Battle Palace BGM TODO: GBS CONVERSION
	song_gbs MUS_B_DOME_LOBBY, gbs_battletowerlobby_Header, 0, 0	@ Battle Dome Lobby & Corridor BGM TODO: GBS CONVERSION
	song_gbs MUS_B_DOME, gbs_battletowertheme_Header, 0, 0	@ Battle Dome Battle & Pre-Battle Rooms BGM TODO: GBS CONVERSION
	song_gbs MUS_B_PIKE, gbs_battletowertheme_Header, 0, 0	@ Battle Pike BGM (All Rooms) TODO: GBS CONVERSION
	song_gbs MUS_B_FACTORY, gbs_battletowertheme_Header, 0, 0	@ Battle Factory BGM (All Rooms) TODO: GBS CONVERSION
	song_gbs MUS_HG_B_TOWER, gbs_battletowertheme_Header, 0, 0	@ BF Battle Tower Battle Rooms & Corridor BGM
	song_gbs MUS_HG_B_TOWER_RECEPTION, gbs_battletowerlobby_Header, 0, 0	@ BF Battle Tower Lobby & Elevator BGM
	
	@ ---------------------------------- @

	@ Pokéathlon
	song_gbs MUS_HG_POKEATHLON_LOBBY, gbs_hg_pokeathlonlobby_Header, 0, 0	@ Trainer Hill Entrance & Elevator
	song_gbs MUS_HG_POKEATHLON_START, gbs_hg_pokeathlonstart_Header, 0, 0	@ Trainer Hill Floor 1 & 2
	song_gbs MUS_HG_POKEATHLON_FINALS, gbs_hg_pokeathlonfinals_Header, 0, 0	@ Trainer Hill Floor 3 & 4
	@song_gbs MUS_HG_POKEATHLON_WINNER, gbs_TODO:_Header, 0, 0	@ Trainer Hill Roof TODO: GBS CONVERSION
	@song_gbs MUS_HG_POKEATHLON_BEFORE, gbs_hg_pokeathlonbefore_Header, 0, 0 @ Unused in HnS	@ TODO: Implement
	@song_gbs MUS_HG_POKEATHLON_EVENT, gbs_hg_pokeathlonevent_Header, 0, 0 @ Unused in HnS	@ TODO: Implement
	@song_gbs MUS_HG_POKEATHLON_RESULTS, gbs_hg_pokeathlonresults_Header, 0, 0 @ Unused in HnS	@ TODO: Implement
	@song_gbs MUS_HG_POKEATHLON_END, gbs_hg_pokeathlonend_Header, 0, 0 @ Unused in HnS	@ TODO: Implement
	
	@ ---------------------------------- @

	@ Character/Event BGM
	song_gbs MUS_HG_EUSINE, gbs_lookmysticalman_Header, 0, 0	@ BGM during Euisine event in Cianwood City TODO: There are more spots where this can be added.
	song_gbs MUS_HG_CLAIR, gbs_clair_Header, 0, 0	@ BGM once Clair enters the Dragon Shrine after the quiz
	song_gbs MUS_HG_FOLLOW_ME_1, gbs_mom_Header, 0, 0	@ Mom's Song (Played when talking to her)
	song_gbs MUS_HG_FOLLOW_ME_2, gbs_showmearound_Header, 0, 0 @ BGM during "Follow Me" events in Cherrygrove and Violet City (School)
	song_gbs MUS_HG_RIVAL_EXIT, gbs_aftertherivalfight_Header, 0, 0	@	@ BGM for after Rival Battles 
	song_gbs MUS_HG_KIMONO_GIRL_DANCE, gbs_dancinghall_Header, 0, 0	@ BGM when Summoning Lugia & Summon Ho-oh
	song_gbs MUS_HG_KIMONO_GIRL, gbs_dancinghall_Header, 0, 0	@ BGM during Kimono Girl events in Violet City, Goldenrod Underground, Ilex Forest, and Ice Path

	@ ---------------------------------- @

	@ National Park / Bug Catching Contest
	song_gbs MUS_HG_NATIONAL_PARK, gbs_nationalpark_Header, 0, 0	@ National Park BGM (Not during Bug Catching Contest)
	song_gbs MUS_HG_BUG_CONTEST_PREP, gbs_contestresults_Header, 0, 0 @ BGM once the Bug Catching Contest is started when talking to an Attendant
	song_gbs MUS_HG_BUG_CATCHING_CONTEST, gbs_bugcatchingcontest_Header, 0, 0 @ National Park BGM (Bug Catching Contest)

	@ ---------------------------------- @

	@ Game Corner
	song_gbs MUS_SLOTS_JACKPOT, gbs_sfx_2ndplace_Header, 2, 2	@ Slots Jackpot / Slots ReelTime success / Roulette max-multiplayer win (never happens) TODO: GBS CONVERSION?
	song_gbs MUS_SLOTS_WIN, gbs_sfx_getcoin_Header, 2, 2	@ Slots/Roulette Win Music TODO: GBS CONVERSION?
	@song_gbs MUS_TOO_BAD, gbs_TODO:_Header, 2, 2	@ Slots ReelTime Lose / Contest Unappeal TODO: GBS CONVERSION?
	@song_gbs MUS_ROULETTE, gbs_TODO:_Header, 0, 0	@ Slots ReelTime BGM TODO: GBS CONVERSION?
	song_gbs MUS_HG_GAME_CORNER, gbs_gamecorner_Header, 0, 0	@ Goldenrod Game Corner BGM & Celadon Game Corner BGM

	@ ---------------------------------- @

	@ Safari Zone
	song_gbs MUS_SAFARI_ZONE, gbs_hg_safarizone_Header, 0, 0	@ Fuchsia City Safari Zone TODO: Change to HG Variant?
	song_gbs MUS_HG_SAFARI_ZONE_GATE, gbs_hg_safarizonegate_Header, 0, 0	@ Gates/Indoors for Safari Zones in Kanto & Johto
	song_gbs MUS_HG_SAFARI_ZONE, gbs_hg_safarizone_Header, 0, 0	@ BGM for Safari Zone areas in Johto Safari Zone

	@ ---------------------------------- @

	@ Contest Music
	@song_gbs MUS_CONTEST, gbs_TODO:_Header, 0, 0	@ Contest Halls BGM TODO: GBS CONVERSION
	@song_gbs MUS_CONTEST_LOBBY, gbs_TODO:_Header, 0, 0		@ Lilycove Contest Lobby BGM (And the Lilycove Contest Hall for some reason) TODO: GBS CONVERSION
	@song_gbs MUS_CONTEST_WINNER, gbs_TODO:_Header, 0, 0		@ Contest Winner BGM TODO: GBS CONVERSION
	@song_gbs MUS_CONTEST_RESULTS, gbs_TODO:_Header, 0, 0	@ BGM during Contest Results TODO: GBS CONVERSION

	@ ---------------------------------- @

	@ Radio
	song_gbs MUS_HG_RADIO_ROCKET, gbs_lakeofragerocketradio_Header, 0, 0 @ BGM during Giovanni scene in Tohjo Falls & When Radio is used during rocket takeover
	song_gbs MUS_HG_RADIO_UNOWN, gbs_ruinsofalphradio_Header, 0, 0	@ Used by the Radio
	song_gbs MUS_HG_RADIO_POKE_FLUTE, gbs_pokeflutechannel_Header, 0, 0	@ Used by the Radio & Snorlax wake up event in Vermilion
	song_gbs MUS_HG_RADIO_OAK, gbs_profoakspokemontalk_Header, 0, 0	@ Used by the Radio
	@song_gbs MUS_HG_RADIO_BUENA, gbs_buenaspassword_Header, 0, 0	@ Unused in HnS - TODO: Skeletonkey36 will implement
	@song_gbs MUS_HG_RADIO_JINGLE, gbs_pokemonchannel_Header, 0, 0	@ Unused in HnS - TODO: Skeletonkey36 will implement
	@song_gbs MUS_HG_RADIO_LULLABY, gbs_pokemonlullaby_Header, 0, 0	@ Unused in HnS - TODO: Skeletonkey36 will implement
	@song_gbs MUS_HG_RADIO_MARCH, gbs_pokemonmarch_Header, 0, 0	@ Unused in HnS - TODO: Skeletonkey36 will implement
	@song_gbs MUS_HG_RADIO_ROUTE101, 0, 0 @ Unused in HnS - TODO: GBS CONVERSION
	@song_gbs MUS_HG_RADIO_ROUTE201, 0, 0 @ Unused in HnS - TODO: GBS CONVERSION
	@song_gbs MUS_HG_RADIO_TRAINER, 0, 0 @ Unused in HnS - TODO: GBS CONVERSION
	@song_gbs MUS_HG_RADIO_VARIETY, 0, 0 @ Unused in HnS - TODO: GBS CONVERSION

	@ ---------------------------------- @

	@ Encounter Stings
	song_gbs MUS_HG_ENCOUNTER_GIRL_1, gbs_lookbeauty_Header, 0, 0	@ Encounter sting for Trainer Classes: Beauty, CoolTrainer (F), Swimmer (F), Parasol Lady, Young Couple, Battle Girl 
	song_gbs MUS_HG_ENCOUNTER_BOY_1, gbs_lookyoungster_Header, 0, 0	@ Encounter sting for Trainer Classes: Youngster, Bug Catcher, School Kid, Bird Keeper, Psychic (M), Camper
	song_gbs MUS_HG_ENCOUNTER_SUSPICIOUS_1, gbs_lookpokemaniac_Header, 0, 0	@ Encounter sting for Trainer Classes: Juggler, Super Nerd, Collector, PokéManiac, Burglar
	song_gbs MUS_HG_ENCOUNTER_SAGE, gbs_looksage_Header, 0, 0	@ Encounter sting for Trainer Classes: Sage, Hex Maniac, Expert (M), Expert (F)
	song_gbs MUS_HG_ENCOUNTER_KIMONO_GIRL, gbs_lookkimonogirl_Header, 0, 0	@ Encounter sting for Kimono Girl Battles
	song_gbs MUS_HG_ENCOUNTER_ROCKET, gbs_lookrocket_Header, 0, 0	@ Encounter sting for Trainer Classes: Team Rocket
	song_gbs MUS_HG_ENCOUNTER_GIRL_2, gbs_looklass_Header, 0, 0	@ Encounter sting for Trainer Classes: Lass, Picnicker, Twins, Psychic (F)
	song_gbs MUS_HG_ENCOUNTER_BOY_2, gbs_lookofficer_Header, 0, 0	@ Encounter sting for Trainer Classes: Policeman (E4 & Champion for Trainer Hill & Battle Pyramid)
	song_gbs MUS_HG_ENCOUNTER_SUSPICIOUS_2, gbs_lookhiker_Header, 0, 0	@ Encounter sting for Trainer Classes: Hiker, Biker, Dragon Tamer, Firebreather, Pokéfan, Fisherman, Sailor, Black Belt, Gentleman, CoolTrainer (M), Guitarist, Swimmer (M)
	song_gbs MUS_HG_ENCOUNTER_RIVAL, gbs_lookrival_Header, 0, 0	@ Encounter sting for Rival battles
	@song_gbs MUS_RG_ENCOUNTER_DEOXYS, gbs_TODO:_Header, 0, 0 @ Encounter sting before static Deoxys encounter TODO: GBS CONVERSION
	
	@ ---------------------------------- @

	@ Battle Music
	song_gbs MUS_HG_VS_WILD, gbs_johtowildbattle_Header, 0, 0	@ BGM during wild battles in Johto
	song_gbs MUS_HG_VS_WILD_KANTO, gbs_kantowildbattle_Header, 0, 0	@ BGM during wild battles in Kanto
	song_gbs MUS_HG_VS_TRAINER, gbs_johtotrainerbattle_Header, 0, 0	@ BGM during battles with Johto trainers
	song_gbs MUS_HG_VS_TRAINER_KANTO, gbs_kantotrainerbattle_Header, 0, 0	@ BGM during battles with Kanto trainers
	song_gbs MUS_HG_VS_ROCKET, gbs_rocketbattle_Header, 0, 0	@ BGM during battles with Team Rocket members
	song_gbs MUS_HG_VS_GYM_LEADER, gbs_johtogymbattle_Header, 0, 0	@ BGM during battles with Johto Gym Leaders & Elite Four members
	song_gbs MUS_HG_VS_GYM_LEADER_KANTO, gbs_kantogymbattle_Header, 0, 0	@ BGM during battles with Kanto Gym Leaders
	song_gbs MUS_HG_VS_RIVAL, gbs_rivalbattle_Header, 0, 0	@ BGM during battles with the player's Rival
	song_gbs MUS_HG_VS_CHAMPION, gbs_championbattle_Header, 0, 0	@ BGM during battles with Champion Lance & Red (TRAINER_CLASS_CHAMPION & TRAINER_CLASS_PKMN_TRAINER_1)
	song_gbs MUS_HG_VS_FRONTIER_BRAIN, gbs_championbattle_Header, 0, 0	@ BGM during battles with Frontier Brains @ TODO: GBS CONVERSION
	
	@ ---------------------------------- @

	@ Legendary Battle Music
	song_gbs MUS_HG_VS_SUICUNE, gbs_suicunebattle_Header, 0, 0	@ BGM during static Suicune encounter
	song_gbs MUS_HG_VS_ENTEI, gbs_suicunebattle_Header, 0, 0	@ BGM during static/roaming Entei encounter (same as Suicune's Music)
	song_gbs MUS_HG_VS_RAIKOU, gbs_suicunebattle_Header, 0, 0	@ BGM during static/roaming Raikou encounter (same as Suicune's Music)
	song_gbs MUS_HG_VS_HO_OH, gbs_suicunebattle_Header, 0, 0	@ BGM during static Ho-oh encounter  TODO: GBS CONVERSION
	song_gbs MUS_HG_VS_LUGIA, gbs_suicunebattle_Header, 0, 0	@ BGM during static Lugia encounter TODO: GBS CONVERSION
	song_gbs MUS_HG_VS_KYOGRE_GROUDON, gbs_suicunebattle_Header, 0, 0	@ BGM for static encounter with Rayquaza  TODO: GBS CONVERSION
	song_gbs MUS_VS_REGI, gbs_suicunebattle_Header, 0, 0	@ Wild and static encounters with Regi Pokémon (Static Encounter not in HnS but setup) (Do new regis trigger this?) TODO: GBS CONVERSION
	song_gbs MUS_VS_KYOGRE_GROUDON, gbs_suicunebattle_Header, 0, 0	@ Wild (not static) encounters with Kyogre and Groudon TODO: GBS CONVERSION
	song_gbs MUS_VS_MEW, gbs_suicunebattle_Header, 0, 0	@ BGM for static Mew Encounter TODO: GBS CONVERSION
	song_gbs MUS_RG_VS_DEOXYS, gbs_suicunebattle_Header, 0, 0	@ BGM for Static Deoxys Encounter TODO: GBS CONVERSION
	song_gbs MUS_RG_VS_MEWTWO, gbs_suicunebattle_Header, 0, 0	@ BGM for Static Mewtwo Encounter TODO: GBS CONVERSION
	song_gbs MUS_RG_VS_LEGEND, gbs_suicunebattle_Header, 0, 0	@ BGM for Static Articuno, Zapdos, Moltres, Latios, & Latias Encounter TODO: GBS CONVERSION
	song_gbs MUS_DP_VS_UXIE_MESPRIT_AZELF, gbs_suicunebattle_Header, 0, 0	@ BGM for Static Jirachi & Celebi  TODO: GBS CONVERSION
	@song_gbs MUS_DP_VS_LEGEND, gbs_suicunebattle_Header, 0, 0	@ BGM for Static Regigigas encounter (Encounter not in HnS but setup)  TODO: GBS CONVERSION
	@song_gbs MUS_PL_VS_REGI, gbs_suicunebattle_Header, 0, 0	@ BGM for Static Regieleki & Regidrago encounters (Encounter not in HnS but setup)  TODO: GBS CONVERSION
	@song_gbs MUS_HG_VS_ARCEUS, 0, 0 @ Unused in HnS  TODO: GBS CONVERSION

	@ ---------------------------------- @

	@ Victory Music
	song_gbs MUS_HG_VICTORY_WILD, gbs_wildpokemonvictory_Header, 0, 0	@ BGM when winning a wild Pokémon battle
	song_gbs MUS_HG_VICTORY_TRAINER, gbs_trainervictory_Header, 0, 0	@ BGM when winning a trainer battle
	song_gbs MUS_HG_VICTORY_GYM_LEADER, gbs_gymleadervictory_Header, 0, 0	@ BGM when winning a battle with Gym Leaders, Elite Four, and Champion
	song_gbs MUS_HG_VICTORY_FRONTIER_BRAIN, gbs_gymleadervictory_Header, 0, 0	@ BGM when winning a battle with a Frontier Brain

	@ ---------------------------------- @

	@ BGM for Various Locations
	song_gbs MUS_HG_POKE_CENTER, gbs_pokemoncenter_Header, 0, 0	@ Johto Pokémon Center BGM TODO: Kanto should technically be this
	song_gbs MUS_RG_POKE_CENTER, gbs_pokemoncenter_Header, 0, 0	@ Kanto Pokémon Center BGM 
	song_gbs MUS_HG_POKE_MART, gbs_hg_poke_mart_Header, 0, 0 @ Poké Mart BGM TODO: GBS CONVERSION
	song_gbs MUS_HG_GYM, gbs_gym_Header, 0, 0	@ Johto Gym BGM TODO: Kanto should technically be this
	song_gbs MUS_RG_GYM, gbs_gym_Header, 0, 0	@ Kanto Gym BGM 
	song_gbs MUS_HG_ELM_LAB, gbs_elmslab_Header, 0, 0	@ Professor Elm's Labratory BGM
	song_gbs MUS_HG_OAK, gbs_profoak_Header, 0, 0	@ Professor Oak's Labratory, Professor Oak events in Olivine Port & Mr. Pokémon's House
	song_gbs MUS_HG_DANCE_THEATER, gbs_dancinghall_Header, 0, 0	@ Ecruteak City Dance Theather & Saffron Dojo VIP Area
	song_gbs MUS_HG_SPROUT_TOWER, gbs_sprouttower_Header, 0, 0	@ Sprout Tower BGM
	song_gbs MUS_HG_UNION_CAVE, gbs_unioncave_Header, 0, 0	@ Ruins of Alph Exterior & Lab, Union Cave, Slowpoke Well, Ilex Forest, Mt Moon Cave, Mt Mortar, Whirl Islands, Tohjo Falls BGM
	song_gbs MUS_HG_RUINS_OF_ALPH, gbs_ruinsofalphinterior_Header, 0, 0	@ Ruins of Alph Underground, Puzzle & Reward Chambers, & Word Rooms BGM
	song_gbs MUS_HG_BURNED_TOWER, gbs_burnedtower_Header, 0, 0	@ Burned Tower BGM
	song_gbs MUS_HG_BELL_TOWER, gbs_tintower_Header, 0, 0	@ Bellchime Trail & Tin Tower BGM
	song_gbs MUS_HG_LIGHTHOUSE, gbs_lighthouse_Header, 0, 0	@ Olivine Lighthouse & Mt Silver (Not exterior entrance or summit)
	song_gbs MUS_HG_TEAM_ROCKET_HQ, gbs_rockethideout_Header, 0, 0	@ Rocket Hideout (Mahogany Shop Script) BGM
	song_gbs MUS_HG_ICE_PATH, gbs_darkcave_Header, 0, 0	@ Dark Cave, Ice Path, Seafoam Islands (Icy Maps) BGM
	song_gbs MUS_HG_DRAGONS_DEN, gbs_dragonsden_Header, 0, 0	@ Dragon's Den BGM
	song_gbs MUS_HG_ROCK_TUNNEL, gbs_mtmoon_Header, 0, 0	@ Kanto Underground Tunnels & Entrances, Rock Tunnel, Diglett's Cave, Cerulean Cave BGM
	song_gbs MUS_HG_MT_MOON_SQUARE, gbs_hg_mt_moon_square_Header, 0, 0 @ BGM in Mt Moon Square (Clefairy nighttime dance area)
	song_gbs MUS_HG_VIRIDIAN_FOREST, gbs_hg_viridian_forest_Header, 0, 0	@ Viridian Forest BGM
	song_gbs MUS_HG_VICTORY_ROAD, gbs_victoryroad_Header, 0, 0	@ Victory Road & Mt Silver Exterior Entrance BGM
	song_gbs MUS_HG_POKEMON_LEAGUE, gbs_indigoplateau_Header, 0, 0	@ R23, Indigo Plateau, & Pokémon League BGM
	song_gbs MUS_HG_ROCKET_TAKEOVER, gbs_rockettheme_Header, 0, 0	@ BGM played in Goldenrod during Rocket Takeover, and Storage and Switches BGM Underground in Goldenrod.
	song_gbs MUS_HG_SS_AQUA, gbs_ssaqua_Header, 0, 0	@ BGM while aboard the SS Aqua
	song_gbs MUS_HG_MAGNET_TRAIN, gbs_magnettrain_Header, 0, 0	@ Played when magnet train arrives during event in Goldenrod and Saffron - Would be played during cutscene on magnet train
	
	@song_gbs MUS_ABANDONED_SHIP, gbs_TODO:_Header, 0, 0	@ Southern Island & Faraway Island BGM TODO: GBS CONVERSION
	@song_gbs MUS_MT_CHIMNEY, gbs_TODO:_Header, 0, 0	@ Seafoam Islands Secret Cave (Groudon Encounter) TODO: GBS CONVERSION
	@song_gbs MUS_WEATHER_KYOGRE, gbs_TODO:_Header, 0, 0 Route 19 Cave (Kyogre Encounter) TODO: GBS CONVERSION
	@song_gbs MUS_RG_SEVII_CAVE, gbs_TODO:_Header, 0, 0 @ Navel Rock Interior BGM TODO: GBS CONVERSION
	@song_gbs MUS_RG_SEVII_ROUTE, gbs_TODO:_Header, 0, 0	@ Navel Rock Exterior BGM TODO: GBS CONVERSION
	@song_gbs MUS_PL_FIGHT_AREA_DAY, gbs_TODO:_Header, 0, 0	@ Trainer Hill Courtyard BGM TODO: GBS CONVERSION
	
	
	song_gbs MUS_EVOLUTION_INTRO, gbs_sfx_evolutionintro_Header, 2, 2	@ Evolution/Hatching Intro
	song_gbs MUS_EVOLUTION, gbs_evolution_Header, 0, 0	@ Evolution/Hatching/Trading BGM
	@ TODO: song_gbs MUS_HG_CAUGHT, gbs_successfulcapture_Header 0, 0 @ Unused in HnS (possible mapping?)
	@ TODO: song_gbs MUS_HG_EVOLUTION, gbs_evolution_Header, 0, 0 @ Unused in HnS (possible mapping?)
	@ TODO: song_gbs MUS_HG_EVOLUTION_NO_INTRO, 0, 0 @ Unused in HnS
	
	
	@ Misc
	song_gbs MUS_HG_MOVE_DELETED, gbs_sfx_movedeleted_Header, 2, 2	@ Move Deleter - Blackthorn
	song_gbs MUS_HG_CYCLING, gbs_bicycle_Header, 0, 0	@ Route 17 (Kanto Bike Path) (Cycling music was cut in favor of having location/map music play.) TODO: Test
	@song_gbs MUS_HG_SURF, gbs_surf_Header, 0, 0 @ Unused in HnS - Surf music was cut in favor of having location/map music play.


	@ Unused Music
	@song_gbs MUS_HG_DEX_RATING_1, 2, 2 @ Unused in HnS - TODO: Implement
	@song_gbs MUS_HG_DEX_RATING_2, 2, 2 @ Unused in HnS - TODO: Implement
	@song_gbs MUS_HG_DEX_RATING_3, 2, 2 @ Unused in HnS - TODO: Implement
	@song_gbs MUS_HG_DEX_RATING_4, 2, 2 @ Unused in HnS - TODO: Implement
	@song_gbs MUS_HG_DEX_RATING_5, 2, 2 @ Unused in HnS - TODO: Implement
	@song_gbs MUS_HG_DEX_RATING_6, 2, 2 @ Unused in HnS - TODO: Implement
	@song_gbs MUS_HG_LETS_GO_TOGETHER, 2, 2 @ Unused in HnS - TODO: Implement?
	@song_gbs MUS_HG_POKEATHLON_READY, 2, 2 @ Unused in HnS - TODO: Implement
	@song_gbs MUS_HG_POKEATHLON_1ST_PLACE, 2, 2 @ Unused in HnS - TODO: Implement
	@song_gbs MUS_HG_RECEIVE_POKEMON, 2, 2 @ Unused in HnS - TODO: Implement?
	@song_gbs MUS_HG_HO_OH_APPEARS, 0, 0 @ Unused in HnS - TODO: Implement?
	@song_gbs MUS_HG_LUGIA_APPEARS, 0, 0 @ Unused in HnS - TODO: Implement?
	@song_gbs MUS_HG_SPIKY_EARED_PICHU, 0, 0 @ Unused in HnS - TODO: Implement Spiky Eared Pichu Event
	@song_gbs MUS_HG_SINJOU_RUINS, 0, 0 @ Unused in HnS - TODO: Implement Sinjoh Ruins
	@song_gbs MUS_HG_POKEWALKER, 0, 0 @ Unused in HnS
	@song_gbs MUS_HG_ETHAN, 0, 0 @ Unused in HnS
	@song_gbs MUS_HG_LYRA, 0, 0 @ Unused in HnS
	@song_gbs MUS_HG_GAME_CORNER_WIN, 0, 0 @ Unused in HnS
	@song_gbs MUS_HG_CARD_FLIP, 2, 2 @ Unused in HnS
	@song_gbs MUS_HG_CARD_FLIP_GAME_OVER, 2, 2 @ Unused in HnS
	@song_gbs MUS_HG_WIN_MINIGAME, 2, 2 @ Unused in HnS
	@song_gbs MUS_HG_MYSTERY_GIFT, 0, 0 @ Unused in HnS
	@song_gbs MUS_HG_WFC, 0, 0 @ Unused in HnS - Multiplayer?
	@song_gbs MUS_HG_WIFI_PLAZA, 0, 0 @ Unused in HnS - Multiplayer?
	@song_gbs MUS_HG_WIFI_MINIGAMES, 0, 0 @ Unused in HnS - Multiplayer?
	@song_gbs MUS_HG_WIFI_PARADE, 0, 0 @ Unused in HnS - Multiplayer?
	@song_gbs MUS_HG_GLOBAL_TERMINAL, 0, 0 @ Unused in HnS - Multiplayer?
	@song_gbs MUS_HG_SPIN_TRADE, 0, 0 @ Unused in HnS - Multiplayer?
	@song_gbs MUS_HG_GTS, 0, 0 @ Unused in HnS - Multiplayer?
	@song_gbs MUS_HG_B_FACTORY, 0, 0 @ Unused in HnS
	@song_gbs MUS_HG_B_HALL, 0, 0 @ Unused in HnS
	@song_gbs MUS_HG_B_ARCADE, 0, 0 @ Unused in HnS
	@song_gbs MUS_HG_B_CASTLE, 0, 0 @ Unused in HnS

	@ ----------------------------------------------------------------------------------------

	
	.4byte 0xFFFFFFFF
