gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} was transferred to\n"
	.string "Someone'S Pc.\p"
	.string "It was placed in \n"
	.string "Box “{STR_VAR_1}.”$"

gText_PkmnTransferredBillsPC::
	.string "{STR_VAR_2} was transferred to\n"
	.string "Bill'S Pc.\p"
	.string "It was placed in \n"
	.string "Box “{STR_VAR_1}.”$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "Box “{STR_VAR_3}” on\n"
	.string "Someone'S Pc was full.\p"
	.string "{STR_VAR_2} was transferred to\n"
	.string "Box “{STR_VAR_1}.”$"

gText_PkmnTransferredBillsPCBoxFull::
	.string "Box “{STR_VAR_3}” on\n"
	.string "Bill'S Pc was full.\p"
	.string "{STR_VAR_2} was transferred to\n"
	.string "Box “{STR_VAR_1}.”$"

gText_NoMoreRoomForPokemon::
	.string "There's no more room for Pokémon!\p"
	.string "The Pokémon Boxes are full and\n"
	.string "can't accept any more!$"

gText_NicknameThisPokemon::
	.string "Do you want to give a nickname to\n"
	.string "this {STR_VAR_1}?$"
