#include "global.h"
#include "text.h"
#include "dynamic_placeholder_text_util.h"
#include "string_util.h"
#include "constants/event_objects.h"
#include "constants/vars.h"

#define COLORS(a)((a))


static EWRAM_DATA const u8 *sStringPointers[8] = {};

void DynamicPlaceholderTextUtil_Reset(void)
{
    const u8 **ptr;
    u8 *fillval;
    const u8 **ptr2;

    ptr = sStringPointers;
    fillval = NULL;
    ptr2 = ptr + (ARRAY_COUNT(sStringPointers) - 1);
    do
    {
        *ptr2-- = fillval;
    } while ((int)ptr2 >= (int)ptr);
}

void DynamicPlaceholderTextUtil_SetPlaceholderPtr(u8 idx, const u8 *ptr)
{
    if (idx < ARRAY_COUNT(sStringPointers))
    {
        sStringPointers[idx] = ptr;
    }
}

u8 *DynamicPlaceholderTextUtil_ExpandPlaceholders(u8 *dest, const u8 *src)
{
    while (*src != EOS)
    {
        if (*src != CHAR_DYNAMIC)
        {
            *dest++ = *src++;
        }
        else
        {
            src++;
            if (sStringPointers[*src] != NULL)
            {
                dest = StringCopy(dest, sStringPointers[*src]);
            }
            src++;
        }
    }
    *dest = EOS;
    return dest;
}

const u8 *DynamicPlaceholderTextUtil_GetPlaceholderPtr(u8 idx)
{
    return sStringPointers[idx];
}

static const u8 sTextColorTable[] =
{
    //FRLG Object events
    //[LOW_NYBBLE]                            = 0xXY, // HIGH_NYBBLE
    /*[OBJ_EVENT_GFX_RED_NORMAL]              = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_RED_BIKE
    [OBJ_EVENT_GFX_RED_SURF]                = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_RED_FIELD_MOVE
    [OBJ_EVENT_GFX_RED_FISH]                = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_RED_VS_SEEKER
    [OBJ_EVENT_GFX_RED_VS_SEEKER_BIKE]      = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_GREEN_NORMAL
    [OBJ_EVENT_GFX_GREEN_BIKE]              = COLORS(NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_GREEN_SURF
    [OBJ_EVENT_GFX_GREEN_FIELD_MOVE]        = COLORS(NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_GREEN_FISH
    [OBJ_EVENT_GFX_GREEN_VS_SEEKER]         = COLORS(NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_GREEN_VS_SEEKER_BIKE
    [OBJ_EVENT_GFX_RS_BRENDAN]              = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_RS_MAY
    [OBJ_EVENT_GFX_LITTLE_BOY]              = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_LITTLE_GIRL
    [OBJ_EVENT_GFX_YOUNGSTER]               = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_BOY
    [OBJ_EVENT_GFX_BUG_CATCHER]             = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_SITTING_BOY
    [OBJ_EVENT_GFX_LASS]                    = COLORS(NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_WOMAN_1
    [OBJ_EVENT_GFX_BATTLE_GIRL]             = COLORS(NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_MAN
    [OBJ_EVENT_GFX_ROCKER]                  = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_FAT_MAN
    [OBJ_EVENT_GFX_WOMAN_2]                 = COLORS(NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_BEAUTY
    [OBJ_EVENT_GFX_BALDING_MAN]             = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_WOMAN_3
    [OBJ_EVENT_GFX_OLD_MAN_1]               = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_OLD_MAN_2
    [OBJ_EVENT_GFX_OLD_MAN_LYING_DOWN]      = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_OLD_WOMAN
    [OBJ_EVENT_GFX_TUBER_M_WATER]           = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_TUBER_F
    [OBJ_EVENT_GFX_TUBER_M_LAND]            = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_CAMPER
    [OBJ_EVENT_GFX_PICNICKER]               = COLORS(NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_COOLTRAINER_M
    [OBJ_EVENT_GFX_COOLTRAINER_F]           = COLORS(NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_SWIMMER_M_WATER
    [OBJ_EVENT_GFX_SWIMMER_F_WATER]         = COLORS(NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_SWIMMER_M_LAND
    [OBJ_EVENT_GFX_SWIMMER_F_LAND]          = COLORS(NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_WORKER_M
    [OBJ_EVENT_GFX_WORKER_F]                = COLORS(NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_ROCKET_M
    [OBJ_EVENT_GFX_ROCKET_F]                = COLORS(NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_GBA_KID
    [OBJ_EVENT_GFX_SUPER_NERD]              = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_BIKER
    [OBJ_EVENT_GFX_BLACKBELT]               = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_SCIENTIST
    [OBJ_EVENT_GFX_HIKER]                   = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_FISHER
    [OBJ_EVENT_GFX_CHANNELER]               = COLORS(NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_CHEF
    [OBJ_EVENT_GFX_POLICEMAN]               = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_GENTLEMAN
    [OBJ_EVENT_GFX_SAILOR]                  = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_CAPTAIN
    [OBJ_EVENT_GFX_NURSE]                   = COLORS(NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_CABLE_CLUB_RECEPTIONIST
    [OBJ_EVENT_GFX_UNION_ROOM_RECEPTIONIST] = COLORS(NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_UNUSED_MALE_RECEPTIONIST
    [OBJ_EVENT_GFX_CLERK]                   = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_MG_DELIVERYMAN
    [OBJ_EVENT_GFX_TRAINER_TOWER_DUDE]      = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_PROF_OAK
    [OBJ_EVENT_GFX_BLUE]                    = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_BILL
    [OBJ_EVENT_GFX_LANCE]                   = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_AGATHA
    [OBJ_EVENT_GFX_DAISY]                   = COLORS(NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_LORELEI
    [OBJ_EVENT_GFX_MR_FUJI]                 = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_BRUNO
    [OBJ_EVENT_GFX_BROCK]                   = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_MISTY
    [OBJ_EVENT_GFX_LT_SURGE]                = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_ERIKA
    [OBJ_EVENT_GFX_KOGA]                    = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_SABRINA
    [OBJ_EVENT_GFX_BLAINE]                  = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_GIOVANNI
    [OBJ_EVENT_GFX_MOM]                     = COLORS(NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_CELIO
    [OBJ_EVENT_GFX_TEACHY_TV_HOST]          = COLORS(NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_GYM_GUY
    [OBJ_EVENT_GFX_ITEM_BALL]               = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_TOWN_MAP
    [OBJ_EVENT_GFX_POKEDEX]                 = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_CUT_TREE
    [OBJ_EVENT_GFX_ROCK_SMASH_ROCK]         = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_PUSHABLE_BOULDER
    [OBJ_EVENT_GFX_FOSSIL]                  = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_RUBY
    [OBJ_EVENT_GFX_SAPPHIRE]                = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_OLD_AMBER
    [OBJ_EVENT_GFX_GYM_SIGN]                = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_SIGN
    [OBJ_EVENT_GFX_TRAINER_TIPS]            = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_CLIPBOARD
    [OBJ_EVENT_GFX_METEORITE]               = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_LAPRAS_DOLL
    [OBJ_EVENT_GFX_SEAGALLOP]               = COLORS(NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_SNORLAX
    [OBJ_EVENT_GFX_SPEAROW]                 = COLORS(NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_CUBONE
    [OBJ_EVENT_GFX_POLIWRATH]               = COLORS(NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_CLEFAIRY
    [OBJ_EVENT_GFX_PIDGEOT]                 = COLORS(NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_JIGGLYPUFF
    [OBJ_EVENT_GFX_PIDGEY]                  = COLORS(NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_CHANSEY
    [OBJ_EVENT_GFX_OMANYTE]                 = COLORS(NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_KANGASKHAN
    [OBJ_EVENT_GFX_PIKACHU]                 = COLORS(NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_PSYDUCK
    [OBJ_EVENT_GFX_NIDORAN_F]               = COLORS(NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_NIDORAN_M
    [OBJ_EVENT_GFX_NIDORINO]                = COLORS(NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_MEOWTH
    [OBJ_EVENT_GFX_SEEL]                    = COLORS(NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_VOLTORB
    [OBJ_EVENT_GFX_SLOWPOKE]                = COLORS(NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_SLOWBRO
    [OBJ_EVENT_GFX_MACHOP]                  = COLORS(NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_WIGGLYTUFF
    [OBJ_EVENT_GFX_DODUO]                   = COLORS(NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_FEAROW
    [OBJ_EVENT_GFX_MACHOKE]                 = COLORS(NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_LAPRAS
    [OBJ_EVENT_GFX_ZAPDOS]                  = COLORS(NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_MOLTRES
    [OBJ_EVENT_GFX_ARTICUNO]                = COLORS(NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_MEWTWO
    [OBJ_EVENT_GFX_MEW]                     = COLORS(NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_ENTEI
    [OBJ_EVENT_GFX_SUICUNE]                 = COLORS(NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_RAIKOU
    [OBJ_EVENT_GFX_LUGIA]                   = COLORS(NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_HO_OH
    [OBJ_EVENT_GFX_CELEBI]                  = COLORS(NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_KABUTO
    [OBJ_EVENT_GFX_DEOXYS_D]                = COLORS(NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_DEOXYS_A
    [OBJ_EVENT_GFX_DEOXYS_N]                = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_SS_ANNE*/

    //HnS Object events
    
    [OBJ_EVENT_GFX_BRENDAN_NORMAL]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_BRENDAN_MACH_BIKE]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_BRENDAN_SURFING]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_QUINTY_PLUMP]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_NINJA_BOY]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_TWIN]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_MR_FUJI]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_GIRL_1]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_BOY]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_CAPTAIN]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_LITTLE_BOY]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_LITTLE_GIRL]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_WORKER_M]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_PICNICKER]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_POLICEMAN]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_WOMAN_3]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_FAT_MAN]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_BILL]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_BALDING_MAN]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_WOMAN_2]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_OLD_MAN_1]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_OLD_WOMAN]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_GYM_GUY]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_COOLTRAINER_F]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_ATTENDANT_M]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_LASS]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_CHEF]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_LINK_RECEPTIONIST]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_OLD_MAN_2]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_ATTENDANT]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_CAMPER]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_SWIMMER_LAND_F]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_MAN]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_WORKER_F]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_YOUNGSTER]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_BUG_CATCHER]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_TRAINER_TOWER_DUDE]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_SWIMMER_LAND_M]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_SUPER_NERD ]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_CHANNELER]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_RAYQUAZA_STILL]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_SWIMMER_M_WATER]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_SWIMMER_F_WATER]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_BLACK_BELT]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_BEAUTY]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_SCIENTIST_M]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_PSYCHIC_M]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_GENTLEMAN]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_SAILOR ]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_FISHER]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_SCOTT]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_BATTLE_GIRL]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_ENGINEER]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_BURGLAR]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_HIKER]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_BIKER]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_CYCLING_TRIATHLETE_F]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_NURSE]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_ITEM_BALL]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_BERRY_TREE]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_BERRY_TREE_EARLY_STAGES]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_BERRY_TREE_LATE_STAGES]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_PROF_ELM]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_COOLTRAINER_M]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_ROCKER]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_FIREBREATHER]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_SAGE]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_BLAINE]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_BROCK]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_MISTY]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_ERIKA]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_SURGE]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_JANINE ]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_SABRINA]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_SHINY_GYARADOS]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_BRANDON]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_GRETA]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_CYCLING_TRIATHLETE_M]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_LUCY]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_NOLAND]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_CUTTABLE_TREE]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_CLERK]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_WOMAN_1]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_KURT]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_BREAKABLE_ROCK]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_PUSHABLE_BOULDER]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_MR_BRINEYS_BOAT]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_MAY_NORMAL   ]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_MAY_MACH_BIKE]              = COLORS(NPC_TEXT_COLOR_FEMALE),           
    [OBJ_EVENT_GFX_MAY_ACRO_BIKE]              = COLORS(NPC_TEXT_COLOR_FEMALE),           
    [OBJ_EVENT_GFX_MAY_SURFING  ]              = COLORS(NPC_TEXT_COLOR_FEMALE),           
    [OBJ_EVENT_GFX_MAY_FIELD_MOVE]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_TRUCK]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_SPENSER]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_TUCKER]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_ANABEL]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_ZIGZAGOON_1]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_UNUSED_WOMAN_4]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_RIVAL_BRENDAN_NORMAL]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_RIVAL_BRENDAN_MACH_BIKE]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_RIVAL_BRENDAN_ACRO_BIKE]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_RIVAL_BRENDAN_SURFING]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_RIVAL_BRENDAN_FIELD_MOVE]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_RIVAL_MAY_NORMAL]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_RIVAL_MAY_MACH_BIKE]              = COLORS(NPC_TEXT_COLOR_FEMALE),     
    [OBJ_EVENT_GFX_RIVAL_MAY_ACRO_BIKE]              = COLORS(NPC_TEXT_COLOR_FEMALE),     
    [OBJ_EVENT_GFX_RIVAL_MAY_SURFING  ]              = COLORS(NPC_TEXT_COLOR_FEMALE),     
    [OBJ_EVENT_GFX_RIVAL_MAY_FIELD_MOVE]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_JUGGLER]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_BRENDAN_UNDERWATER]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_MAY_UNDERWATER]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_TUBER_M]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_TRAIN_FRONT]              = COLORS(NPC_TEXT_COLOR_FEMALE),             
    [OBJ_EVENT_GFX_SCIENTIST_F]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_KIMONO_GIRL]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_ROCKET_M]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_ROCKET_F]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_PETREL]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_ARIANA]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_WILL]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_KOGA]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_BRUNO]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_KAREN]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_FALKNER]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_BUGSY]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_WHITNEY]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_MORTY]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_JASMINE]              = COLORS(NPC_TEXT_COLOR_FEMALE),                 
    [OBJ_EVENT_GFX_CHUCK]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_BLUE]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_PRYCE]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_LANCE]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_STEVEN]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_SILVER]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_LITTLE_BOY_3]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_BRENDAN_FISHING]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_MAY_FISHING ]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_HOT_SPRINGS_OLD_WOMAN]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_SS_TIDAL]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_LEGENDARY_SHADOW ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_PICHU_DOLL       ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_PIKACHU_DOLL     ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_MARILL_DOLL      ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_TOGEPI_DOLL      ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_CYNDAQUIL_DOLL   ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_CHIKORITA_DOLL   ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_TOTODILE_DOLL    ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_JIGGLYPUFF_DOLL  ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_MEOWTH_DOLL      ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_CLEFAIRY_DOLL    ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_DITTO_DOLL       ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_SMOOCHUM_DOLL    ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_TREECKO_DOLL     ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_TORCHIC_DOLL     ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_MUDKIP_DOLL      ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_DUSKULL_DOLL     ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_WYNAUT_DOLL      ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_BALTOY_DOLL      ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_KECLEON_DOLL     ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_AZURILL_DOLL     ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_SKITTY_DOLL      ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_SWABLU_DOLL      ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_GULPIN_DOLL      ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_LOTAD_DOLL       ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_SEEDOT_DOLL      ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_PIKA_CUSHION     ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_ROUND_CUSHION    ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_KISS_CUSHION     ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_ZIGZAG_CUSHION   ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_SPIN_CUSHION     ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_DIAMOND_CUSHION  ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_BALL_CUSHION     ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_GRASS_CUSHION    ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_FIRE_CUSHION     ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_WATER_CUSHION    ]                     = COLORS(NPC_TEXT_COLOR_MON),       
    [OBJ_EVENT_GFX_BIG_SNORLAX]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_BIG_RHYDON_DOLL]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_LAPRAS]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_BIG_VENUSAUR_DOLL ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_BIG_CHARIZARD_DOLL]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_BIG_BLASTOISE_DOLL]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_BIG_WAILMER_DOLL  ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_BIG_REGIROCK_DOLL ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_BIG_REGICE_DOLL   ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_BIG_REGISTEEL_DOLL]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_LATIAS ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_LATIOS]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_GBA_KID]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_EUSINE]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_BRENDAN_WATERING]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_MAY_WATERING]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_BRENDAN_DECORATING]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_MAY_DECORATING]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_PROTON]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_ARCHER]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_KYOGRE_FRONT   ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_GROUDON_FRONT  ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_FOSSIL         ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_TRAIN_MID      ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_REGICE         ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_TRAIN_BACK     ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_WHIRLPOOL      ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_KECLEON        ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_KYOGRE_ASLEEP  ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_GROUDON_ASLEEP ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_RAYQUAZA       ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_ZIGZAGOON_2    ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_PIKACHU        ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_AZUMARILL      ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_SLOWPOKE_NO_TAIL]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_KECLEON_BRIDGE_SHADOW ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_TUBER_M_WATER]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_AZURILL]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_MOM]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_LINK_BRENDAN]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_LINK_MAY]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_CLAIR]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_PROF_OAK]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_POOCHYENA]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_KYOGRE_SIDE]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_GROUDON_SIDE]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_MYSTERY_GIFT_MAN]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_TUBER_F]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_NURSE_CHANSEY ]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_DUSCLOPS]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_RED_NORMAL]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_SUDOWOODO]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_MEW]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_RED]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_LEAF]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_DEOXYS]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_DEOXYS_TRIANGLE]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_GIOVANNI]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_LINK_RS_BRENDAN]              = COLORS(NPC_TEXT_COLOR_MALE),
    [OBJ_EVENT_GFX_LINK_RS_MAY]              = COLORS(NPC_TEXT_COLOR_FEMALE),
    [OBJ_EVENT_GFX_LUGIA]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_HOOH]                     = COLORS(NPC_TEXT_COLOR_MON),
    [OBJ_EVENT_GFX_SPECIES(BULBASAUR) ... OBJ_EVENT_GFX_SPECIES(ARCEUS)]= COLORS(NPC_TEXT_COLOR_MON),
    // Bug: Follower object events that are in the overworld (the ones that use "OBJ_EVENT_GFX_MON_BASE+SPECIES_XXXXX")
    // aren't recognized as their own object events and use the color of the number of the species. 

    // Eg. "OBJ_EVENT_GFX_MON_BASE+SPECIES_KINGLER" uses number 98, as Kingler is the 98th species. "OBJ_EVENT_GFX_UNUSED_WOMAN_4" is also 98, and uses red text.
    // So, every "OBJ_EVENT_GFX_MON_BASE+SPECIES_KINGLER" will have red text. 
};

u8 GetColorFromTextColorTable(u16 graphicId)
{
    u32 test = graphicId;

    if (test >= NELEMS(sTextColorTable))
        return 3;
    else
        return (sTextColorTable[graphicId]);
}
